[package]
name = "habitat_common"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
workspace = "../../"

[dependencies]
ansi_term = "*"
libc = "*"
log = "*"
pbr = "0.2" # lock until ready to support 0.3+ interface
regex = "*"
retry = "*"
rustc-serialize = "*"
term = "*"
time = "*"
toml = { version = "*", features = ["serde"] }

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_depot_client]
path = "../builder-depot-client"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "*"
winapi = "*"

[dev-dependencies]
tempdir = "*"

[features]
functional = []
